FirstProj/Models/Card.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FirstProj.Models;

namespace FirstProj.Models
{
    public class Card
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_Card { get; set; }
        [Key]
        [ForeignKey("Users")]
        public int ID_User { get; set; }
        [Key]
        public CardType ID_Type { get; set; }
        [Key]
        public string CardNumber { get; set; }
        [Key]
        public DateTime CardExpDate { get; set; }
        [Key]
        public int CVV { get; set; }
        [Required]
        [Display(Name = "Balance")]
        public decimal Balance { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public List<string> Cards { get; set; }
        


    }
}

FirstProj/Models/CardType.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace FirstProj.Models
{
    public enum CardType
    {
        Debit = 1,
        Credit = 2
    }
}

FirstProj/Controllers/CardController.cs
using MRSUTWeb.BusinessLogic;
using MRSUTWeb.BusinessLogic.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MRSUTWeb.Domain.Entities.Card;
using FirstProj.Models;
using MRSUTWeb.BusinessLogic.DBModel;
using MRSUTWeb.BusinessLogic.Core;
using MRSUTWeb.Domain.Entities.User;
using System.Text.RegularExpressions;

namespace FirstProj.Controllers
{
    public class CardController : Controller
    {
        private readonly ICard _context;
        private readonly CardApi _cardApi = new CardApi();

        public CardController()
        {
            var bl = new BusinessLogic();
            _context = bl.GetCardBL();
        }

        public ActionResult RequestCard()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RequestCard(Card register)
        {
            var xKeyCookie = Request.Cookies["X-KEY"];
            if (xKeyCookie != null)
            {
                CardDbTable card = new CardDbTable
                {
                    //ID_User = _context.GetUserByCookie(xKeyCookie.Value).ID_User,
                    //CardNumber = _cardApi.GenerateCardNumber(),
                    //ExpiryDate = _cardApi.GenerateExpiryDate(),
                    //CVV = _cardApi.GenerateCVV(),
                    Balance = register.Balance,
                    ID_Type = (CardTypeDbTable)register.ID_Type,
                    //I want to get number for specific card type , 1 for debit card and 2 for credit card


                    //UserName = _context.GetUserFromDatabase(_context.GetUserByCookie(xKeyCookie.Value).ID_User).Username,
                    //UserSurname = _context.GetUserFromDatabase(_context.GetUserByCookie(xKeyCookie.Value).ID_User).Name
                };
                _context.InsertCard_M(card, xKeyCookie);
                //redirect to logged home
                return RedirectToAction("LogedHome", "LogedUserHome");
            }

            return RedirectToAction("LogedHome", "LogedUserHome");
        }
        // function to get user data from database
        public ActionResult UserCards()
        {
            var xKeyCookie = Request.Cookies["X-KEY"];
            if (xKeyCookie != null)
            {
                var user = _context.GetUserByCookie(xKeyCookie.Value);
                if (user != null)
                {
                    var cardsDb = _context.GetUserCards(user.ID_User);
                    var cards = cardsDb.Select(card => new Card
                    {

                        CardNumber = card.CardNumber,
                        UserName = card.Name,
                        UserSurname = card.UserSurname,
                        Balance = card.Balance,
                        CardExpDate = card.ExpiryDate

                    }).ToList();

                    return PartialView("_UserCardsPartial", cards);
                }
            }

            return PartialView("_UserCardsPartial", new List<Card>());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Transfer(string senderCardNumber, string receiverCardNumber, decimal amount, string senderExpireDate, string senderCVV)
        {
            /*if (string.IsNullOrEmpty(senderExpireDate) || string.IsNullOrEmpty(senderCVV))
            {
                ViewBag.Error = "Data de expirare și CVV-ul sunt obligatorii.";
                return RedirectToAction("TransferNotSucces");
            }


             if (!Regex.IsMatch(senderExpireDate, @"^(0[1-9]|1[0-2])/\d{4}$") || !Regex.IsMatch(senderCVV, @"^\d{3}$"))
            {
                ViewBag.Error = "Data de expirare sau CVV incorecte.";
                return RedirectToAction("TransferNotSucces");
            } */
            try
            {
                _cardApi.TransferBalance(senderCardNumber, receiverCardNumber, amount);
                return RedirectToAction("TransferSucces");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("TransferNotSucces");
            }
        }
        public ActionResult TransferSucces()
        {
            return View();
        }
        public ActionResult TransferNotSucces()
        {
            return View();
        }
    }
}

FirstProj/Views/Card/RequestCard.cshtml
@model FirstProj.Models.Card
@{
    ViewBag.Title = "RequestCard";
    Layout = "~/Views/Shared/_LayoutWithUser.cshtml";
}
<style>
    .form-control {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .btn-primary {
        padding: 10px 20px;
        background-color: #007bff;
        border: none;
        color: white;
        cursor: pointer;
        border-radius: 5px;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }
</style>
<h2>Request a New Card</h2>
<br />
<br />
<br />
<br />
<br />
<br />

@using (Html.BeginForm("RequestCard", "Card", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.ID_Type)
        @Html.DropDownListFor(m => m.ID_Type, new SelectList(Enum.GetValues(typeof(FirstProj.Models.CardType))), new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Balance)
        @Html.TextBoxFor(m => m.Balance, new { @class = "form-control", type = "number" })
    </div>
    <button type="submit" class="btn btn-primary">Request Card</button>
}

FirstProj/Views/Card/TransferNotSucces.cshtml
@{
     ViewBag.Title = "TransferNotSucces";
     Layout = "~/Views/Shared/_LayoutWithUser.cshtml";
}

<br />
<br />
<br />
<br />
<br />
<br />
<h1>Transfer esuat! Suma sau datele cardului sunt incorecte.</h1>
<h1>@Html.ActionLink("Inapoi", "ClientHome", "LogedUserHome")</h1>

FirstProj/Views/Card/TransferSucces.cshtml
@{
     ViewBag.Title = "TransferSucces";
     Layout = "~/Views/Shared/_LayoutWithUser.cshtml";
}

<br />
<br />
<br />
<br />
<br />
<br />
<h1>Transferul a fost efectuat cu succes!</h1>
<h1>@Html.ActionLink("Cabinet Personal", "ClientHome", "LogedUserHome")</h1>

FirstProj/Views/Card/_UserCardsPartial.cshtml
@model IEnumerable<FirstProj.Models.Card>
@{
     ViewBag.Title = "_UserCardsPartial";
}

@if (!Model.Any())
{
     <p>No cards available.</p>
}
else
{
     <p>Numărul de carduri: @Model.Count()</p>

     
          foreach (var card in Model)
          {
          <span class="card">
                         <span class="bank-name">Bad Bank</span>
                         <span class="card-number">@card.CardNumber</span>
                         <span class="owner-name">@card.UserName @card.UserSurname</span>
                         <span class="balance">@card.Balance MDL</span>
                         <span class="expire-date">@card.CardExpDate.ToString("MM/yy")</span>
                         
         
         </span>           
          }
     
}

<style>
     .card {
          position: relative;
          width: 400px;
          height: 200px;
          border: 2px solid #000;
          background-color: #808080;
          margin-top: 20px;
     }
          

          .card .bank-name {
               font-size: 25px;
               position: absolute;
               top: 10px;
               right: 10px;
               color: white;
          }

          .card .balance {
               position: absolute;
               top: 60%;
               left: 50%;
               transform: translate(-50%, -50%);
               color: white;
          }

          .card .card-number {
               position: absolute;
               top: 50%;
               left: 50%;
               transform: translate(-50%, -50%);
               color: white;
          }

          .card .owner-name {
               position: absolute;
               bottom: 10px;
               left: 10px;
               color: white;
          }

          .card .expire-date {
               position: absolute;
               bottom: 10px;
               right: 10px;
               color: white;
          }
</style>