FirstProj/Controllers/ForgetPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FirstProj.Models;
using MRSUTWeb.BusinessLogic.Core;
using MRSUTWeb.Web.Models;
using static MRSUTWeb.BusinessLogic.Core.UserApi;

namespace FirstProj.Controllers
{
    public class ForgetPasswordController : Controller
    {
        public ActionResult ForgetPassword()
        {
            return View();
        }
        private readonly UserApi _userApi;

        public ForgetPasswordController()
        {
            _userApi = new UserApi();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendCode(string username)
        {
            _userApi.SendResetCode(username);
            return RedirectToAction("EnterCode");
        }

        public ActionResult EnterCode()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordViewModel model)
        {

            if (!ModelState.IsValid)
            {

                return View("EnterCode", model);
            }

            if (!_userApi.VerifyResetCode(model.Username, model.Code))
            {

                ModelState.AddModelError("Code", "Invalid reset code");
                return View("EnterCode", model);
            }

            _userApi.ResetPassword(model.Username, model.Code, model.NewPassword);

            return RedirectToAction("PasswordResetSuccess");
        }


        public ActionResult PasswordResetSuccess()
        {
            return View();
        }




    }

}

FirstProj/Controllers/LoginController.cs
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using AutoMapper;
    using MRSUTWeb.BusinessLogic;
    using MRSUTWeb.BusinessLogic.Interfaces;
    using MRSUTWeb.Domain.Entities.User;
    using FirstProj.Models;


    namespace FirstProj.Controllers
    {

        public class LoginController : Controller
        {
            private readonly ISession _session;
            public LoginController()
            {
                var bl = new BusinessLogic();
                _session = bl.GetSessionBL();
            }
            //GET: Login
            public ActionResult LogIn()
            {
            var xKeyCookie = Request.Cookies["X-KEY"];
            if (xKeyCookie != null)
            {
                var user = _session.GetUserByCookie(xKeyCookie.Value);
                if (user != null)
                {
                    ViewBag.UserRole = user.ID_Type_user;
                    return RedirectToAction("LogedHome", "LogedUserHome");
                }
            }
            
        return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(MRSUTWeb.Web.Models.UserLogin login)
        {
            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<MRSUTWeb.Web.Models.UserLogin, ULoginData>());
                var mapper = config.CreateMapper();
                var data = mapper.Map<ULoginData>(login);
                data.LoginIp = Request.UserHostAddress;
                data.LoginDateTime = DateTime.Now;
                var userLogin = _session.UserLogin(data);
                if (userLogin.Status)
                {
                    HttpCookie cookie = _session.GenCookie(login.Username);
                    ControllerContext.HttpContext.Response.Cookies.Add(cookie);
                    HttpCookie xKeyCookie = new HttpCookie("X-KEY", cookie.Value);
                    ControllerContext.HttpContext.Response.Cookies.Add(xKeyCookie);

                    return RedirectToAction("LogedHome", "LogedUserHome");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                }
            }
            return View("LogIn", login);
        }

        public UserMinimal GetUserDetails(string authToken)
            {
                return _session.GetUserByCookie(authToken);
            }
            public ActionResult LogOut()
            {
                var cookie = Request.Cookies["X-KEY"];
                if (cookie != null)
                {
                    cookie.Expires = DateTime.Now;
                    Response.Cookies.Add(cookie);
                }
                return View();
            }

        }
    }

FirstProj/Controllers/RegisterController.cs
using FirstProj.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using System.Net;
using MRSUTWeb.BusinessLogic;
using MRSUTWeb.BusinessLogic.Interfaces;
using MRSUTWeb.Domain.Entities.User;


namespace FirstProj.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ISession _session;
        public RegisterController()
        {
            var bl = new BusinessLogic();
            _session = bl.GetSessionBL();
        }
        // GET: Register
        public ActionResult NewUser()
        {
            return View();
        }

        // POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewUser(UserRegister register)
        {
            if (ModelState.IsValid)
            {
                //create a new user
                URegister newUser = new URegister
                {
                    Name = register.Name,
                    Surname = register.Surname,
                    Username = register.Username,
                    Email = register.Email,
                    Password = register.Password
                };
                _session.Insert_RegisterUserAction(newUser);
                //_session.SendEmail_Register(newUser);

                ViewBag.Message = "User registered successfully";

            }
            return View();


        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ConfirmateAccount()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EnterCode(VerificationCode model)
        {
            var xKeyCookie = Request.Cookies["X-KEY"];

            if (xKeyCookie != null)
            {
                var user = _session.GetUserByCookie(xKeyCookie.Value);
                if (user != null)
                {
                    //check inputed code with the one in the database

                    if (user.Code == model.Code)
                    {
                        //update user role
                        //_session.UpdateUserRole(xKeyCookie, model.Code);
                        //update user role to 1
                        ViewBag.UserRole = user.ID_Type_user;
                        user.ID_Type_user = 1;
                        _session.UpdateUserRole(xKeyCookie, user.ID_Type_user);
                        return RedirectToAction("ClientHome", "LogedUserHome");

                    }
                    else
                    {
                        ViewBag.UserRole = user.ID_Type_user;
                        return RedirectToAction("LogedHome", "LogedUserHome");

                    }
                }
            }
            return View();
        }

    }
}

FirstProj/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutWithUser.cshtml";
}

<h2>Index</h2>

FirstProj/Views/Login/LogIn.cshtml
@{
    ViewBag.Title = "LogIn";
    Layout = "~/Views/Shared/_LayoutWithUser.cshtml";
}

@model MRSUTWeb.Web.Models.UserLogin

<style>
    .panel {
        max-width: 400px;
        margin: 0 auto;
        margin-top: 50px;
    }

    .panel-heading {
        text-align: center;
    }

    .panel-body {
        padding: 20px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .login {
        background-color: #007bff;
        border-color: #007bff;
    }

        .login:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
</style>

<br />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Logare utilizator</h2>
                </div>
                <div class="panel-body">
                    @if (!String.IsNullOrEmpty(ViewBag.Message))
                    {
                        <div class="alert alert-danger">@ViewBag.Message</div>
                    }
                    else
                    {
                        using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group" style="margin-bottom: 15px;">
                                @Html.LabelFor(m => m.Username, new { @class = "control-label" })
                                <div style="margin: 15px;">
                                    @Html.EditorFor(m => m.Username, new { htmlAttributes = new { @class = "form-control", style = "width: 300px; padding: 10px;" } })
                                    @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div style="margin-bottom: 15px; margin-right: 30px;">
                                    @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                                    @Html.EditorFor(m => m.Password, new { htmlAttributes = new { @class = "form-control", maxlength = 50, style = "padding: 10px;" } })
                                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-block login">Logare</button>
                                </div>
                            </div>
                        }
                    }
                    <p><br />@Html.ActionLink("Ați uitat parola?", "ForgetPassword", "ForgetPassword")</p>
                    <p>@Html.ActionLink("Nu aveți cont?", "NewUser", "Register")</p>
                </div>
            </div>
        </div>
    </div>
</div>